version: "3.9"

services:
  server:
    build: .
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/attendance/
    ports:
      - "8000:8000"